image: ghcr.io/rophy/testing-library-docs:ci-02d93a0

pages:
  stage: deploy
  variables:
    DEPLOY_ENV: gitlab
  script:
    - ln -s /deps/root/node_modules ./node_modules
    - ln -s /deps/plugin/node_modules ./plugins/docusaurus-plugin-kms-sync/node_modules
    - npm run build
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - main
