image: node:20

pages:
  stage: deploy
  variables:
    DEPLOY_ENV: gitlab
  script:
    - npm ci
    - cd plugins/docusaurus-plugin-kms-sync && npm ci && cd ../..
    - npm run build
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - main
